import getpass
import colorama
from colorama import Fore
import discord
from discord.ext import commands
import os
import getpass
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))

os.system(f'cls & mode 85,20 & title PHAZIFY AUTOPRESSER')
user = input("Name: ")
print(f'''{Fore.GREEN}
 _    __   __    __   ______   ________  ______  ________  __      __ 
|       \ |  \  |  \ /      \ |        \|      \|        \|  \    /  |
| $$$$$$$\| $$  | $$|  $$$$$$\ \$$$$$$$$ \$$$$$$| $$$$$$$$ \$$\  /  $$
| $$__/ $$| $$__| $$| $$__| $$    /  $$   | $$  | $$__      \$$\/  $$ 
| $$    $$| $$    $$| $$    $$   /  $$    | $$  | $$  \      \$$  $$  
| $$$$$$$ | $$$$$$$$| $$$$$$$$  /  $$     | $$  | $$$$$       \$$$$   
| $$      | $$  | $$| $$  | $$ /  $$___  _| $$_ | $$          | $$    
| $$      | $$  | $$| $$  | $$|  $$    \|   $$ \| $$          | $$    
 \$$       \$$   \$$ \$$   \$$ \$$$$$$$$ \$$$$$$ \$$           \$$    
             ___________LOGGED IN AS: {user}___________                                             
                        PHAZIFY MADE THIS
                                                                                    
        ''' + Fore.GREEN)

token = input("Enter token: ")
sex = input("Keyword: ")
print("READY TO RAPE BLACKS")
###### CODEZZZZZ#######
@client.event
async def on_message(message):
    channel = message.channel
    print("BITCH GOT RAPED:",message.content)
    if message.content.endswith(sex):

        await message.channel.send('SO THIS NOBODY SPEAKING TO ME?')
        await message.channel.send('https://preview.redd.it/ipi9k0c814f61.png?width=598&format=png&auto=webp&s=721ff92fa49303a988e7dbd64bfca1f343bbed8d')
        await message.channel.send('UR NOTHING')
        await message.channel.send('FUCKING BITCH ARE U READY TO GET BITCHED?')
        await message.channel.send('LOOLO')
        await message.channel.send('U AINT FASTER')
        await message.channel.send('UNKNOWN ON THE WALK')
        await message.channel.send('GET MANIPULATED')
        await message.channel.send('LOOOO')
        await message.channel.send('UR GETTING HOED')
        await message.channel.send('LOOOO')
        await message.channel.send('BENCH DOWN')
        await message.channel.send('LOOOLOOLOL')
        await message.channel.send('DISCORD WARRIOR')
        await message.channel.send('SHITT')
        await message.channel.send('STAY ALIVE')
        await message.channel.send('DONT FAINT')
        await message.channel.send('TAKE THE PRESSURE')
        await message.channel.send('https://cdn.discordapp.com/attachments/975054396297711656/1016362278125318244/951.gif')
        await message.channel.send('GOBLIN')
        await message.channel.send('LOOOOL')
        await message.channel.send('LOOOOO')
        await message.channel.send('COME BAKE')
        await message.channel.send('SHITTY CHATPACKER')
        await message.channel.send('U DONT HARM ANYONE')
        await message.channel.send('IHARMLESS FUCKER')
        await message.channel.send('LOOOOL')
        await message.channel.send('I WANT ')
        await message.channel.send('YOUR')
        await message.channel.send('HEAD')
        await message.channel.send('I GET WHATEVER')
        await message.channel.send('I DESIRE')
        await message.channel.send('YOU UNSPOILED RAT')
        await message.channel.send('ALBINO FUCK')
        await message.channel.send('ILL BITCH YOU')
        await message.channel.send('GET UP')
        await message.channel.send('IT AINT TIME')
        await message.channel.send('TO SLEEP FAGGOT')
        await message.channel.send('FIGHT THE JINS')
        await message.channel.send('FUCKING EMO')
        await message.channel.send('CUT URSELF')
        await message.channel.send('LOLOL')
        await message.channel.send('OLOLOL')
        await message.channel.send('LOLOLOL')
        await message.channel.send('https://cdn.discordapp.com/attachments/975054396297711656/1016361118626762802/95.gif')
        await message.channel.send('ILL PASS U A SEIZURE')
        await message.channel.send('HAVE A STROKE')
        await message.channel.send('ILL HUMBLE YOU FROM LEFT AND RIGHT')
        await message.channel.send('CUMSLUT')
        await message.channel.send('LOLOLOLO')
        await message.channel.send('U AINT LOUD')
        await message.channel.send('LET ME MAKE IT FAIR')
        await message.channel.send('https://tenor.com/view/discord-turn-up-gif-22192050')
        await message.channel.send('WHO ARE YOU')
        await message.channel.send('LMAO')
        await message.channel.send('YOU DONT KNOW')
        await message.channel.send('WHO YOU MESSING WITH')
        await message.channel.send('SHITTER')
        await message.channel.send('LOLOLOL')
        await message.channel.send('OLOLOLO')
        await message.channel.send('LOLOLOL')
        await message.channel.send('KKK ONTOP')
        await message.channel.send('MANSLAUGHTER UR BITCH ASS')
        await message.channel.send('PHAZIFY REALLING FLAMING YOU')
        await message.channel.send('GET BITCHED IN YOUR COFFIN')
        await message.channel.send('ASS')
        await message.channel.send('SLOW')
        await message.channel.send('TYPER')
        await message.channel.send('UR SLOW COMPARED TO ME')
        await message.channel.send('KEEP WAFFLING')
        await message.channel.send('SLEEP')
        await message.channel.send('TAKE YOUR REST')
        await message.channel.send('HEILLLL HITLERRRR')
        await message.channel.send('https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Flag_of_Tsagaan_Khas_%28Dayar_Mongol%29.png/1200px-Flag_of_Tsagaan_Khas_%28Dayar_Mongol%29.png')
        await message.channel.send('GASS')
        await message.channel.send('UR')
        await message.channel.send('JEW')
        await message.channel.send('FAMILY')
        await message.channel.send('OLOLO')
        await message.channel.send('OLOLOL')
        await message.channel.send('LOLOLOLE')
        await message.channel.send('KEEP CHATTING')
        await message.channel.send('LMAOAOAO')
        await message.channel.send('DISCORD')
        await message.channel.send('BLACK BITCH')
        await message.channel.send('LOOOL')
        await message.channel.send('LOLOL')
        await message.channel.send('WEAKLING')
        await message.channel.send('MY SEXSLAVE')
        await message.channel.send('SATIFY MY DICK')
        await message.channel.send('ED')
        await message.channel.send('BOY')
        await message.channel.send('GETTING ENDED')
        await message.channel.send('ILL BURN UR FLAG')
        await message.channel.send('https://ichef.bbci.co.uk/news/976/cpsprodpb/6B77/production/_113611572_9fab05fe-5098-4803-a790-b34a922b0479.png')
        await message.channel.send('LIEUTENANT PHAZIFY BITCHING YOU')
        await message.channel.send('COME')
        await message.channel.send('PACKK')
        await message.channel.send('LOOLOOLOLOL')
        await message.channel.send('COME WANNA BE MY NEW GOON?')
        await message.channel.send('COME')
        await message.channel.send('DIE IRRELEVANT BLACK')
        await message.channel.send('RETARD')
        await message.channel.send('SLEEP ON UR FATHER')
        await message.channel.send('LOOO')
        await message.channel.send('LOOL')
        await message.channel.send('OOOOOOOOL')
        await message.channel.send('LOOOL')
        await message.channel.send('SHITTER')
        await message.channel.send('WE WILL BITCH YOU')
        await message.channel.send('https://media.discordapp.net/attachments/908045179737481287/1015843682999615508/attachment-1.gif')
        await message.channel.send('SACRIFICE UR LIFE FOR THOMAS ROBB')
        await message.channel.send('LMAAOOO')
        await message.channel.send('LOOLOLOL')
        await message.channel.send('😹😹😹😹😹😹😹')
        await message.channel.send('SLIDE ME')
        await message.channel.send('THE BLACK')
        await message.channel.send('WHOPPERS')
        await message.channel.send('HEAD RIGHT THE FUCK')
        await message.channel.send('NOW')
        await message.channel.send('UR DUMB AUTISTIC DISABLED FATHER')
        await message.channel.send('GOT HIS THROAT POPPED')
        await message.channel.send('LOO')
        await message.channel.send('https://media.discordapp.net/attachments/908045179737481287/1015810500560441385/image0-25-1.gif')
        await message.channel.send('LOOKAT UR DAD')
        await message.channel.send('CRY ABOUT IT')
        await message.channel.send('IM THE NIGGER DESTROYED')
        await message.channel.send('NIGGERIZATION MUST STOP')
        await message.channel.send('SON OF A WHORE')
        await message.channel.send('UNKNOWNS TALKING?')
        await message.channel.send('LOLOLOL')
        await message.channel.send('OLOLOL')
        await message.channel.send('LOLOLOL')
        await message.channel.send('U BELONG TO UR FATHER')
        await message.channel.send('LOLOLOL')
        await message.channel.send('OLOL')
        await message.channel.send('OLLOLOL')
        await message.channel.send('KKK TAKES OVER THE WORLD')
        await message.channel.send('WE RUN WE RULE')
        await message.channel.send('LOL9OLOLO')
        await message.channel.send('LOLOLOL')
        await message.channel.send('LOLOLOL')
        await message.channel.send('LOLOLOL')
        await message.channel.send('SHITTTYYY FAGGOT')
        await message.channel.send('WE ARE LEGION')
        await message.channel.send('EXPECT US')
        await message.channel.send('BLACK MORON')
        await message.channel.send('CUNT ASS NIGGA')
        await message.channel.send('U CANT BEAT ME')
        await message.channel.send('CHATMOVE FASTER')
        await message.channel.send('UR A DWARF COMPARED TO ME')
        await message.channel.send('NIGGA HAS DWARF GROWTH')
        await message.channel.send('BASTARD')
        await message.channel.send('PRICKY')
        await message.channel.send('ILL SHOVE A BLOODY NAPKIN IN UR FACE')
        await message.channel.send('FINGER URSELF WITH THAT CACTUS')
        await message.channel.send('UR AUTISTICNESS WONT DISAPPEAR')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('OUOLOLOLOL')
        await message.channel.send('FUCKING REFUGEE')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('LOOOLOOL')
        await message.channel.send('IMMIGRANT LMAOAOAO')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('LMAAOOO ILL KO THE FUCK OUTTA YOU')
        await message.channel.send('LITTLE RAT')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('U CANT TAKE ME ON LMAOOO')
        await message.channel.send('UR AUTISTICNESS WONT DISAPPEAR')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('https://media.discordapp.net/attachments/932540531869880390/962087934570410014/A2C66C28-91A6-4802-978A-FB4B2ECF2414.gif')
        await message.channel.send('BIGGEST HERO OF THIS ENTIRE CENTURY')
        await message.channel.send('GEORGE FLOYD WAS UR UNCLE?')
        await message.channel.send('CRY ABOUT IT')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('ILL KISS UR MOMS CHEEKS')
        await message.channel.send('STEP IN VC AND COME GET BITCHED')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('MORON')
        await message.channel.send('CRACKED JUNK')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('ILL NUT IN UR MOM')
        await message.channel.send('ILL MAKE HER RIDE MY FUCKING DICK')
        await message.channel.send('TILL SHE BEGS ME TO STOP')
        await message.channel.send('LOLOLOL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('BEGG ME')
        await message.channel.send('DID U GIVE UP?')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('ILL SLUT DOWN UR GRANDMA')
        await message.channel.send('DISGRACE TO THE PACKING COMMUNITY')
        await message.channel.send('DUBBLE UP')
        await message.channel.send('UR MOMS A BUBBLE GIRL')
        await message.channel.send('BELLY BUT ASS HAVING NIGGER')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('TAKE A ICE BATH')
        await message.channel.send('U AINT SURVIVING')
        await message.channel.send('LOOLOOOL')
        await message.channel.send('TROLL')
        await message.channel.send('LOLOLOLOL')
        await message.channel.send('OLOLOLOLOL')
        await message.channel.send('PHAZIFY OUT U GOT BITCHED BY KKK NAZI CSSR')


client.run(token, bot=False)
